server:
  port: 10010
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/
zuul:
  prefix: /api #添加路由前缀
  routes:
    item-service: /item/**
    upload-serivce:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
#ribbon:
#  eureka:
#    enabled: false
#user-service:
#  ribbon:
#    listOfServers: http://localhost:8081
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断时间5000ms
ribbom:
  ConnectionTimeout: 1000 #ribbon连接超时时长
  ReadTimeout: 3500 # ribbon读取超市时长
  MaxAutoRetries: 0 #当前服务重试次数
  MaxAutoRetriesNextServer: 0 #切换服务重试次数
